server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
